media:
  input: public/images
  output: /images

content:
  - name: posts
    label: 文章
    type: collection
    path: src/content/posts
    filename: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    view:
      fields: [title, published, category, draft]
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: published
        label: 发布日期
        type: date
        required: true
      - name: description
        label: 摘要
        type: text
      - name: image
        label: 封面图
        type: image
      - name: tags
        label: 标签
        type: list
        options:
          item:
            type: string
      - name: category
        label: 分类
        type: string
      - name: draft
        label: 草稿
        type: boolean
      - name: lang
        label: 语言
        type: string
      - name: pinned
        label: 置顶
        type: boolean
      - name: body
        label: 正文
        type: rich-text
